"""
services/intelligence/scoring_engine.py

Produces a 0-100 score for each competitor across 6 market dimensions.
The 6 dimensions are UNIVERSAL (Speed, Range, Price, Experience, Support, Sustainability)
but the KEYWORDS used to measure each dimension are GENERATED BY THE LLM
based on the competitor's actual industry context — making this fully industry-agnostic.

Data sources:
  - Snapshot.clean_text  → keyword frequency (supply side)
  - HiringSignal         → department focus (investment signals)
  - Reddit mentions      → sentiment / demand side
"""
import json
import logging
import re

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# Universal dimensions (framework stays constant, vocabulary adapts)
# ─────────────────────────────────────────────────────────────────────────────
DIMENSIONS = ["speed", "range", "price", "experience", "support", "sustainability"]

DIMENSION_DESCRIPTIONS = {
    "speed":          "How fast or efficiently the product/service is delivered",
    "range":          "Breadth of products, services, or categories offered",
    "price":          "Value-for-money, discounts, pricing strategy signals",
    "experience":     "UX quality, personalization, loyalty, and gamification",
    "support":        "Customer service quality, resolution speed, helpdesk",
    "sustainability": "Environmental responsibility, eco-friendly operations",
}

# ─────────────────────────────────────────────────────────────────────────────
# Fallback keywords used ONLY when LLM is unavailable
# (generic enough to work in most B2C contexts)
# ─────────────────────────────────────────────────────────────────────────────
FALLBACK_KEYWORDS = {
    "speed":          ["fast", "quick", "instant", "express", "rapid", "immediate", "real-time"],
    "range":          ["variety", "category", "selection", "catalogue", "assortment", "broad", "wide"],
    "price":          ["discount", "offer", "affordable", "value", "cheap", "save", "cashback", "deal"],
    "experience":     ["easy", "seamless", "personali", "curated", "reward", "loyalty", "recommend"],
    "support":        ["support", "care", "refund", "return", "24x7", "helpdesk", "resolution"],
    "sustainability": ["eco", "green", "recycle", "biodegradable", "sustainable", "carbon", "organic"],
}

FALLBACK_HIRING = {
    "speed":          ["logistics", "supply chain", "operations", "delivery"],
    "range":          ["category", "merchandising", "procurement", "buying"],
    "price":          ["pricing", "finance", "growth"],
    "experience":     ["product", "design", "engineering", "ux"],
    "support":        ["customer success", "support", "cx"],
    "sustainability": ["sustainability", "esg", "green"],
}


# ─────────────────────────────────────────────────────────────────────────────
# LLM-based taxonomy generator
# ─────────────────────────────────────────────────────────────────────────────

def generate_keyword_taxonomy(industry_context: str) -> dict:
    """
    Ask the LLM to generate domain-specific keywords for each dimension
    given a brief of the competitors' industry and sample content.

    Returns:
        {
          "speed":    ["keyword1", "keyword2", ...],
          "range":    [...],
          ...
          "_hiring": {
            "speed":  ["job title keyword", ...],
            ...
          }
        }
    Falls back gracefully to FALLBACK_KEYWORDS + FALLBACK_HIRING on any failure.
    """
    try:
        from services.llm.ollama_client import OllamaClient
        client = OllamaClient("http://localhost:11434", "gemma3:4b")

        prompt = f"""You are a market research analyst building a competitive intelligence scoring system.

Industry context:
{industry_context}

For each of the 6 dimensions below, output 8-12 specific keywords or short phrases that would SIGNAL competitor activity in that dimension when found in website copy, press releases, or job descriptions. Make these highly specific to the given industry.

Dimensions:
- speed: {DIMENSION_DESCRIPTIONS['speed']}
- range: {DIMENSION_DESCRIPTIONS['range']}
- price: {DIMENSION_DESCRIPTIONS['price']}
- experience: {DIMENSION_DESCRIPTIONS['experience']}
- support: {DIMENSION_DESCRIPTIONS['support']}
- sustainability: {DIMENSION_DESCRIPTIONS['sustainability']}

Also output job title keywords for each dimension (terms that would appear in hiring ads).

Output ONLY valid JSON in this EXACT format, no markdown, no explanation:
{{
  "keywords": {{
    "speed": ["kw1", "kw2", ...],
    "range": ["kw1", "kw2", ...],
    "price": ["kw1", "kw2", ...],
    "experience": ["kw1", "kw2", ...],
    "support": ["kw1", "kw2", ...],
    "sustainability": ["kw1", "kw2", ...]
  }},
  "hiring": {{
    "speed": ["job title term1", ...],
    "range": ["job title term1", ...],
    "price": ["job title term1", ...],
    "experience": ["job title term1", ...],
    "support": ["job title term1", ...],
    "sustainability": ["job title term1", ...]
  }}
}}"""

        logger.info("[ScoringEngine] Generating dynamic keyword taxonomy via LLM...")
        response = client.generate(prompt)

        # Strip markdown fences if present
        match = re.search(r'```(?:json)?\s*(.*?)\s*```', response, re.DOTALL)
        cleaned = match.group(1) if match else response.strip()
        # Sometimes LLM wraps in outer braces with extra text — find first { to last }
        start = cleaned.find('{')
        end   = cleaned.rfind('}')
        if start != -1 and end != -1:
            cleaned = cleaned[start:end+1]

        parsed = json.loads(cleaned)
        kws    = parsed.get("keywords", {})
        hiring = parsed.get("hiring", {})

        # Validate all 6 dimensions are present — fall back per-dim if missing
        taxonomy = {}
        hiring_taxonomy = {}
        for dim in DIMENSIONS:
            taxonomy[dim]         = kws.get(dim)    or FALLBACK_KEYWORDS[dim]
            hiring_taxonomy[dim]  = hiring.get(dim)  or FALLBACK_HIRING[dim]

        logger.info(f"[ScoringEngine] Dynamic taxonomy generated: {list(taxonomy.keys())}")
        taxonomy["_hiring"] = hiring_taxonomy
        return taxonomy

    except Exception as e:
        logger.warning(f"[ScoringEngine] LLM taxonomy generation failed: {e} — using fallback keywords")
        result = dict(FALLBACK_KEYWORDS)
        result["_hiring"] = dict(FALLBACK_HIRING)
        return result


# ─────────────────────────────────────────────────────────────────────────────
# Scoring helpers
# ─────────────────────────────────────────────────────────────────────────────

def _keyword_score(text: str, keywords: list) -> float:
    """Count keyword hits in text and normalize to 0-1 (capped)."""
    text = text.lower()
    hits = sum(1 for kw in keywords if kw.lower() in text)
    return min(hits / max(len(keywords) * 0.3, 1), 1.0)


def score_competitor(
    competitor_name: str,
    snapshots_text: list,
    hiring_departments: list,
    reddit_posts: list,
    taxonomy: dict | None = None,
) -> dict:
    """
    Score a competitor across all 6 dimensions.
    taxonomy: output of generate_keyword_taxonomy(). If None, uses fallback.
    Returns: { "speed": 72, "range": 45, ... }
    """
    if taxonomy is None:
        taxonomy = dict(FALLBACK_KEYWORDS)
        taxonomy["_hiring"] = dict(FALLBACK_HIRING)

    hiring_taxonomy = taxonomy.get("_hiring", FALLBACK_HIRING)

    combined_snapshot = " ".join(snapshots_text)
    combined_reddit   = " ".join(
        (p.get("title", "") + " " + p.get("text", "")) for p in reddit_posts
    )
    combined_hiring   = " ".join(str(d).lower() for d in hiring_departments)

    scores = {}
    for dim in DIMENSIONS:
        kws      = taxonomy.get(dim, FALLBACK_KEYWORDS[dim])
        hire_kws = hiring_taxonomy.get(dim, FALLBACK_HIRING[dim])

        snap_s   = _keyword_score(combined_snapshot, kws)
        hire_s   = _keyword_score(combined_hiring,   hire_kws)
        reddit_s = _keyword_score(combined_reddit,    kws)

        composite = (snap_s * 0.5) + (hire_s * 0.3) + (reddit_s * 0.2)
        scores[dim] = max(5, round(composite * 100))

    logger.info(f"[Scoring] {competitor_name}: {scores}")
    return scores


# ─────────────────────────────────────────────────────────────────────────────
# Whitespace angle finder
# ─────────────────────────────────────────────────────────────────────────────

def find_whitespace_angles(
    all_scores: dict,
    reddit_by_competitor: dict,
    taxonomy: dict | None = None,
) -> list:
    """
    Identifies dimensions where avg competitor score is LOW (<55)
    but Reddit demand is HIGH — real customer need, no competitor supply.
    Returns sorted list of angle dicts.
    """
    if taxonomy is None:
        taxonomy = dict(FALLBACK_KEYWORDS)

    competitors = list(all_scores.keys())
    if not competitors:
        return []

    angles = []
    for dim in DIMENSIONS:
        avg_score = sum(all_scores[c].get(dim, 50) for c in competitors) / len(competitors)

        all_reddit = " ".join(
            p.get("title", "") + " " + p.get("text", "")
            for posts in reddit_by_competitor.values()
            for p in posts
        ).lower()
        kws           = taxonomy.get(dim, FALLBACK_KEYWORDS[dim])
        reddit_demand = _keyword_score(all_reddit, kws)

        if avg_score < 55 and reddit_demand > 0.08:
            opportunity_score = round((1 - avg_score / 100) * 80 + reddit_demand * 20)
            impact = min(5, max(1, round(opportunity_score / 20)))
            angles.append({
                "dimension":         dim,
                "title":             _angle_title(dim),
                "description":       _angle_description(dim, avg_score, competitors, all_scores),
                "opportunity_score": opportunity_score,
                "impact":            impact,
                "tag":               _angle_tag(dim),
            })

    angles.sort(key=lambda x: -x["opportunity_score"])
    return angles[:5]


def _angle_title(dim: str) -> str:
    return {
        "speed":          "Fast Delivery / Execution Gap",
        "range":          "Category Assortment Whitespace",
        "price":          "Value-for-Money Positioning",
        "experience":     "Frictionless UX Opportunity",
        "support":        "Support Experience Deficit",
        "sustainability": "Eco-Conscious Positioning",
    }.get(dim, dim.title())


def _angle_tag(dim: str) -> str:
    return {
        "speed":          "SPEED WHITESPACE",
        "range":          "CATEGORY GAP",
        "price":          "VALUE SIGNAL",
        "experience":     "UX OPPORTUNITY",
        "support":        "CRITICAL RISK",
        "sustainability": "EMERGENT TREND",
    }.get(dim, "OPPORTUNITY")


def _angle_description(dim: str, avg_score: float, competitors: list, all_scores: dict) -> str:
    weakest = min(competitors, key=lambda c: all_scores[c].get(dim, 100))
    return {
        "speed":          f"Competitors average {avg_score:.0f}/100 on speed/execution signals. {weakest} shows the least investment — first-mover advantage is available.",
        "range":          f"Average category-depth score is {avg_score:.0f}/100. No competitor strongly owns a niche vertical — a curated assortment creates immediate differentiation.",
        "price":          f"Value messaging scores {avg_score:.0f}/100. Customers seek transparent pricing and cashback parity — a subscription 'Price Lock' plan captures high-LTV users.",
        "experience":     f"UX investment signals average {avg_score:.0f}/100. Personalization and gamification are under-leveraged — loyalty features can drive 15%+ engagement lifts.",
        "support":        f"Support quality scored {avg_score:.0f}/100. Manual resolution dominates — AI-powered Tier-1 resolution could reduce handle time 40% and push NPS above 70.",
        "sustainability": f"Only {avg_score:.0f}/100 on eco-messaging. Eco-conscious demographics show willingness to pay a 12-15% premium — currently an unclaimed market position.",
    }.get(dim, f"Dimension '{dim}' scored {avg_score:.0f}/100 — a potential positioning opportunity.")
